[package]
name = "canyon-rpc"
version = "2.0.0"
authors = ["Parity Technologies <admin@parity.io>"]
edition = "2018"
license = "Apache-2.0"
homepage = "https://substrate.dev"
repository = "https://github.com/paritytech/substrate/"

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]

[dependencies]
jsonrpc-core = "15.1.0"

sc-client-api = { git = "https://github.com/canyon-network/substrate", branch = "w3f-grant-1" }
sc-consensus-babe = { git = "https://github.com/canyon-network/substrate", branch = "w3f-grant-1" }
sc-consensus-babe-rpc = { git = "https://github.com/canyon-network/substrate", branch = "w3f-grant-1" }
sc-consensus-epochs = { git = "https://github.com/canyon-network/substrate", branch = "w3f-grant-1" }
sc-chain-spec = { git = "https://github.com/canyon-network/substrate", branch = "w3f-grant-1" }
sc-finality-grandpa = { git = "https://github.com/canyon-network/substrate", branch = "w3f-grant-1" }
sc-finality-grandpa-rpc = { git = "https://github.com/canyon-network/substrate", branch = "w3f-grant-1" }
sc-keystore = { git = "https://github.com/canyon-network/substrate", branch = "w3f-grant-1" }
sc-rpc = { git = "https://github.com/canyon-network/substrate", branch = "w3f-grant-1" }
sc-rpc-api = { git = "https://github.com/canyon-network/substrate", branch = "w3f-grant-1" }
sc-sync-state-rpc = { git = "https://github.com/canyon-network/substrate", branch = "w3f-grant-1" }
sp-api = { git = "https://github.com/canyon-network/substrate", branch = "w3f-grant-1" }
sp-block-builder = { git = "https://github.com/canyon-network/substrate", branch = "w3f-grant-1" }
sp-blockchain = { git = "https://github.com/canyon-network/substrate", branch = "w3f-grant-1" }
sp-keystore = { git = "https://github.com/canyon-network/substrate", branch = "w3f-grant-1" }
sp-consensus = { git = "https://github.com/canyon-network/substrate", branch = "w3f-grant-1" }
sp-consensus-babe = { git = "https://github.com/canyon-network/substrate", branch = "w3f-grant-1" }
sp-runtime = { git = "https://github.com/canyon-network/substrate", branch = "w3f-grant-1" }
sp-transaction-pool = { git = "https://github.com/canyon-network/substrate", branch = "w3f-grant-1" }

pallet-mmr-rpc = { git = "https://github.com/canyon-network/substrate", branch = "w3f-grant-1" }
pallet-transaction-payment-rpc = { git = "https://github.com/canyon-network/substrate", branch = "w3f-grant-1" }
substrate-frame-rpc-system = { git = "https://github.com/canyon-network/substrate", branch = "w3f-grant-1" }

canyon-primitives = { path = "../primitives" }
canyon-runtime = { path = "../runtime" }
