[package]
name = "canyon-executor"
version = "2.0.0"
authors = ["Parity Technologies <admin@parity.io>"]
description = "Substrate node implementation in Rust."
edition = "2018"
license = "Apache-2.0"
homepage = "https://substrate.dev"
repository = "https://github.com/paritytech/substrate/"

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]

[dependencies]
codec = { package = "parity-scale-codec", version = "2.0.0" }
trie-root = "0.16.0"

sc-executor = { git = "https://github.com/canyon-network/substrate", branch = "w3f-grant-1" }
sp-core = { git = "https://github.com/canyon-network/substrate", branch = "w3f-grant-1" }
sp-keystore = { git = "https://github.com/canyon-network/substrate", branch = "w3f-grant-1" }
sp-io = { git = "https://github.com/canyon-network/substrate", branch = "w3f-grant-1" }
sp-state-machine = { git = "https://github.com/canyon-network/substrate", branch = "w3f-grant-1" }
sp-trie = { git = "https://github.com/canyon-network/substrate", branch = "w3f-grant-1" }
frame-benchmarking = { git = "https://github.com/canyon-network/substrate", branch = "w3f-grant-1" }

canyon-primitives = { path = "../primitives" }
canyon-runtime = { path = "../runtime" }

[dev-dependencies]
criterion = "0.3.0"
wat = "1.0"

frame-support = { git = "https://github.com/canyon-network/substrate", branch = "w3f-grant-1" }
frame-system = { git = "https://github.com/canyon-network/substrate", branch = "w3f-grant-1" }
pallet-balances = { git = "https://github.com/canyon-network/substrate", branch = "w3f-grant-1" }
pallet-contracts = { git = "https://github.com/canyon-network/substrate", branch = "w3f-grant-1" }
pallet-grandpa = { git = "https://github.com/canyon-network/substrate", branch = "w3f-grant-1" }
pallet-im-online = { git = "https://github.com/canyon-network/substrate", branch = "w3f-grant-1" }
pallet-indices = { git = "https://github.com/canyon-network/substrate", branch = "w3f-grant-1" }
pallet-session = { git = "https://github.com/canyon-network/substrate", branch = "w3f-grant-1" }
pallet-timestamp = { git = "https://github.com/canyon-network/substrate", branch = "w3f-grant-1" }
pallet-transaction-payment = { git = "https://github.com/canyon-network/substrate", branch = "w3f-grant-1" }
pallet-treasury = { git = "https://github.com/canyon-network/substrate", branch = "w3f-grant-1" }
sp-application-crypto = { git = "https://github.com/canyon-network/substrate", branch = "w3f-grant-1" }
sp-consensus-babe = { git = "https://github.com/canyon-network/substrate", branch = "w3f-grant-1" }
sp-runtime = { git = "https://github.com/canyon-network/substrate", branch = "w3f-grant-1" }
sp-externalities = { git = "https://github.com/canyon-network/substrate", branch = "w3f-grant-1" }
substrate-test-client = { git = "https://github.com/canyon-network/substrate", branch = "w3f-grant-1" }

[features]
wasmtime = [
	"sc-executor/wasmtime",
]
wasmi-errno = [
	"sc-executor/wasmi-errno",
]
stress-test = []
